apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-guestbook.fullname" . }}
  labels:
    {{- include "helm-guestbook.labels" . | nindent 4 }}
data:
  config.conf: |
    # Configuration file
    key: value
